### ISSUE TITLE
Incorrect error handling for checking for game binary

### ISSUE THREAD

**Issue by StarVore** [Donimax/satisfactory-docker#4]
Line 49 of run.sh is looking for UE4Server-Linux-Shipping
Checking install files of the dedicated server, it creates the file "UnrealServer-Linux-Shipping" instead, causing the docker image to crash with error "Game binary is missing."

Proposed solution: Update condition at line 49 to look for either "UE4Server-Linux-Shipping" OR "UnrealServer-Linux-Shipping"

**Comment by Donimax** [comment]
@StarVore should be fixed now.
